---
##CSU default commands on every Arista Device
fabric_name: CSU
vlan_internal_order: 
  allocation: descending
  range:
    beginning: 2
    ending: 4094

#Ansible login stuff for CVAAS
ansible_host: www.cv-staging.corp.arista.io
ansible_user: cvaas
ansible_password: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjY0MjcyOTgsImRzbiI6ImFuc2libGUiLCJkc3QiOiJhY2NvdW50IiwiZXhwIjoxNzUxMzc2MTc0LCJpYXQiOjE3MjI0MzIxODIsIm9naSI6NTAyNzk0OCwib2duIjoibm1vb3JlLWxhYiIsInNpZCI6ImM2NTliMTExNzQxMzQ5OTU0NWQxZmEzOTBhNzg0Nzc0MDI3Yjg0YjQ2NTEzZmFlYzM0ODlhNzI1ZDQxNDgyZGUtSlluNFQwdE5ZZXROYWtDU1VnOFN6TDJxejhsQlZueWtiVHNWWjEzdyJ9.PjXi6tsBdgvMQJogVli9jEo75Kp-2zY0tCNhFaOUZn1Epf9RF0Z62c1sVBMFk9DMfzjTAfOtplfjydc-DeGlUA
ansible_connection: httpapi
ansible_network_os: eos
ansible_httpapi_use_ssl: True
ansible_httpapi_validate_certs: True
ansible_httpapi_port: 443

#Local User Accounts
local_users: 
  - name: ansible
    privilege: 15
    role: network-admin
    sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true

#TACACS/AAA configuration
tacacs_servers:
  hosts:
    - host: 1.1.1.1
      vrf: default
      key: testkey1

aaa_authentication:
  login:
    default:  "group tacacs+ local"
    console:  "group tacacs+ local"

timezone: MST

#Defaulting to MGMT VRF and OOB Management interface
mgmt_interface: Management0
mgmt_interface_vrf: MGMT
mgmt_gateway: 192.168.3.1

#Name Servers
name_servers: 
  - 8.8.8.8
  - 208.67.222.222

#NTP using MGMT VRF/interface
ntp_settings: 
  server_vrf: use_mgmt_interface_vrf
  servers:
    - name: 192.168.1.6

#Logging using default interface
logging:
  vrfs:
    - name: default
      # Source interface name.
      source_interface: Management1
      hosts:
        - name: 10.100.201.199

#SNMP per CSU using the default VRF
snmp_server:
  contact: "noc@colostate.edu"
  location: "E7 row 5 cab 5"
  hosts:
    - host: "10.100.201.190"
      vrf: default
      version: 2c
      community: "csUn0c"
  communities:
    - name: pcm_mAnAg3
      access: rw
    - name: csUn0c
      access: ro

banners:
  login:  " TESTING"
# \  /SSSSSS            /SS             /SS                     /SS                 /SS \n
#  \ /SS__  SS          |__/            | SS                    | SS                | SS \n
#   | SS  \\ SS  /SSSSSS  /SS  /SSSSSSS /SSSSSS    /SSSSSS       | SS        /SSSSSS | SSSSSSS \n
#   | SSSSSSSS /SS__  SS| SS /SS_____/|_  SS_/   |____  SS      | SS       |____  SS| SS__  SS \n
#   | SS__  SS| SS  \\__/| SS|  SSSSSS   | SS      /SSSSSSS      | SS        /SSSSSSS| SS  \\ SS \n
#   | SS  | SS| SS      | SS \\____  SS  | SS /SS /SS__  SS      | SS       /SS__  SS| SS  | SS \n
#   | SS  | SS| SS      | SS /SSSSSSS/  |  SSSS/|  SSSSSSS      | SSSSSSSS|  SSSSSSS| SSSSSSS/ \n
#   |__/  |__/|__/      |__/|_______/    \\___/   \\_______/      |________/ \\_______/|_______/ \n
#   ********************************************************************************************** \n
#  \                                         This is a lab, only a lab."


    
p2p_uplinks_mtu: 1500 

default_interfaces: 
  - types: [ spine ]
    platforms: [ default ]
    uplink_interfaces: [ Ethernet1-2 ]
    downlink_interfaces: [ Ethernet1-8 ]
  - types: [ l3leaf ]
    platforms: [ default ]
    uplink_interfaces: [ Ethernet1-2 ]
    mlag_interfaces: [ Ethernet20-21 ]
    downlink_interfaces: [ Ethernet8 ]
  - types: [ l2leaf ]
    platforms: [ default ]
    uplink_interfaces: [ Ethernet11-12 ]


