---
# ansible_user: "{{ lookup('ansible.builtin.env', 'CVUSER', default='cvaas') }}"
ansible_user: cvaas
ansible_host: www.cv-staging.corp.arista.io
ansible_password: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjY0MjcyOTgsImRzbiI6ImFuc2libGUiLCJkc3QiOiJhY2NvdW50IiwiZXhwIjoxNzUxMzc2MTc0LCJpYXQiOjE3MjI0MzIxODIsIm9naSI6NTAyNzk0OCwib2duIjoibm1vb3JlLWxhYiIsInNpZCI6ImM2NTliMTExNzQxMzQ5OTU0NWQxZmEzOTBhNzg0Nzc0MDI3Yjg0YjQ2NTEzZmFlYzM0ODlhNzI1ZDQxNDgyZGUtSlluNFQwdE5ZZXROYWtDU1VnOFN6TDJxejhsQlZueWtiVHNWWjEzdyJ9.PjXi6tsBdgvMQJogVli9jEo75Kp-2zY0tCNhFaOUZn1Epf9RF0Z62c1sVBMFk9DMfzjTAfOtplfjydc-DeGlUA
ansible_connection: httpapi
ansible_network_os: eos
ansible_httpapi_use_ssl: True
ansible_httpapi_validate_certs: True
ansible_httpapi_port: 443