---
default_interfaces: 
  - types: [ spine ]
    platforms: [ default ]
    uplink_interfaces: [ Ethernet1-2 ]
    downlink_interfaces: [ Ethernet1-8 ]
  - types: [ l3leaf ]
    platforms: [ default ]
    uplink_interfaces: [ Ethernet1-2 ]
    mlag_interfaces: [ Ethernet20-21 ]
    downlink_interfaces: [ Ethernet8 ]
mgmt_gateway: 192.168.3.1

spine:
  defaults:
    platform: cEOSLab
    loopback_ipv4_pool: 10.0.1.0/24
    bgp_as: 65100

  nodes: 
    - name: spine1-dc1
      id: 25
      mgmt_ip: 192.168.3.5/24
    - name: spine2-dc1
      id: 26
      mgmt_ip: 192.168.3.6/24

l3leaf:
  defaults:
    platform: cEOSLab  
    loopback_ipv4_pool: 10.0.1.0/24
    loopback_ipv4_offset: 3
    bgp_as: 65100
    vtep_loopback_ipv4_pool: 10.1.1.0/24
    uplink_switches: ['spine1-dc1', 'spine2-dc1']
    uplink_ipv4_pool: 10.255.1.0/24
    mlag_peer_ipv4_pool: 10.255.255.0/25
    mlag_peer_l3_ipv4_pool: 10.255.255.128/25
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  
  node_groups:
    - group: DC1_L3_LEAF1
      bgp_as: 65101
      nodes:
        - name: leaf1a-dc1
          id: 1
          mgmt_ip: 192.168.3.2/25
          uplink_switch_interfaces:
            - Ethernet1
            - Ethernet1

        - name: leaf1b-dc1
          id: 2
          mgmt_ip: 192.168.3.19/25
          uplink_switch_interfaces:
            - Ethernet2
            - Ethernet2

    - group: DC1_L3_LEAF2
      bgp_as: 65102
      nodes:
        - name: leaf2a-dc1
          id: 3
          mgmt_ip: 192.168.3.3/25
          uplink_switch_interfaces:
            - Ethernet3
            - Ethernet3

        - name: leaf2b-dc1
          id: 4
          mgmt_ip: 192.168.3.17/25
          uplink_switch_interfaces:
            - Ethernet4
            - Ethernet4

    - group: DC1_L3_LEAF3
      bgp_as: 65103
      nodes:
        - name: leaf3a-dc1
          id: 5
          mgmt_ip: 192.168.3.4/25
          uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
        - name: leaf3b-dc1
          id: 6
          mgmt_ip: 192.168.3.18/25
          uplink_switch_interfaces:
            - Ethernet6
            - Ethernet6

