---
### group_vars/NETWORK_SERVICES.yml

tenants:
  # Definition of tenants. Additional level of abstraction to VRFs
  - name: TENANT1
    # Number used to generate the VNI of each VLAN by adding the VLAN number in this tenant.
    mac_vrf_vni_base: 10000
    vrfs:
      # VRF definitions inside the tenant.
      - name: SERVERS
        # VRF VNI definition.
        vrf_vni: 1
        # Enable VTEP Network diagnostics
        # This will create a loopback with virtual source-nat enable to perform diagnostics from the switch.
        vtep_diagnostic:
          # Loopback interface number
          loopback: 1
          # Loopback ip range, a unique ip is derived from this ranged and assigned
          # to each l3 leaf based on it's unique id.
          loopback_ip_range: 10.10.1.1/27
        svis:
          # SVI definitions.
          - id: 10
            # SVI Description
            name: GOODSERVERS
            enabled: true
            # IP anycast gateway to be used in the SVI in every leaf.
            ip_address_virtual: 172.16.10.1/24
          - id: 20
            name: OKSERVERS
            enabled: true
            ip_address_virtual: 172.16.20.1/24
      - name: SNEAKYSNEAKY
        vrf_vni: 2
        vtep_diagnostic:
          loopback: 2
          loopback_ip_range: 10.255.11.1/27
        svis:
          - id: 21
            name: VRF11_VLAN21
            enabled: true
            ip_address_virtual: 10.10.21.1/24
          - id: 22
            name: VRF11_VLAN22
            enabled: true
            ip_address_virtual: 10.10.22.1/24


