hostname: camsw2
is_deployed: false
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.3.1
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 8.8.8.8
  vrf: MGMT
- ip_address: 208.67.222.222
  vrf: MGMT
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
  no_spanning_tree_vlan: '4094'
local_users:
- name: admin
  privilege: 15
  role: network-admin
  no_password: true
- name: ansible
  privilege: 15
  role: network-admin
  sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920
clock:
  timezone: MST
vrfs:
- name: MGMT
  ip_routing: false
management_interfaces:
- name: Management0
  description: oob_management
  shutdown: false
  vrf: MGMT
  ip_address: 172.16.100.106/24
  gateway: 192.168.3.1
  type: oob
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ntp:
  local_interface:
    name: Management0
    vrf: MGMT
  servers:
  - name: 192.168.1.6
    vrf: MGMT
    preferred: true
vlans:
- id: 4094
  tenant: system
  name: MLAG_PEER
  trunk_groups:
  - MLAG
- id: 11
  name: ACNS_Mgmt
  tenant: main
- id: 103
  name: ACNS_Services_103
  tenant: main
- id: 408
  name: Cardkey_DataCenter
  tenant: main
- id: 553
  name: Windows_Unix_MGMT
  tenant: main
- id: 592
  name: Security_Cameras
  tenant: main
- id: 918
  name: Cluster_comm_10.2.103
  tenant: main
- id: 920
  name: VM_Mgmt
  tenant: main
- id: 922
  name: Vmotion
  tenant: main
- id: 1000
  name: san_0
  tenant: main
- id: 1001
  name: san_1
  tenant: main
vlan_interfaces:
- name: Vlan4094
  description: MLAG_PEER
  shutdown: false
  no_autostate: true
  mtu: 1500
  ip_address: 192.168.0.59/31
port_channel_interfaces:
- name: Port-Channel47
  description: MLAG_PEER_camsw1_Po47
  type: switched
  shutdown: false
  mode: trunk
  trunk_groups:
  - MLAG
ethernet_interfaces:
- name: Ethernet47
  peer: camsw1
  peer_interface: Ethernet47
  peer_type: mlag_peer
  description: MLAG_PEER_camsw1_Ethernet47
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 47
    mode: active
- name: Ethernet48
  peer: camsw1
  peer_interface: Ethernet48
  peer_type: mlag_peer
  description: MLAG_PEER_camsw1_Ethernet48
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 47
    mode: active
- name: Ethernet1
  peer: UNIX_R5C7U1-2_CAMSYSPIVOT1
  peer_interface: Eth0/3
  peer_type: server
  description: UNIX_R5C7U1-2_CAMSYSPIVOT1_Eth0/3
  shutdown: false
  type: switched
  mode: access
  vlans: '553'
  spanning_tree_portfast: edge
  spanning_tree_bpduguard: enabled
- name: Ethernet2
  peer: UNIX_R5C7U1-2_CAMSYSPIVOT1
  peer_interface: Eth0/2
  peer_type: server
  description: UNIX_R5C7U1-2_CAMSYSPIVOT1_Eth0/2
  shutdown: false
  type: switched
  mode: access
  vlans: '1001'
  spanning_tree_portfast: edge
- name: Ethernet3
  peer: UNIX_R5C7U1-2_CAMSYSPIVOT1
  peer_interface: Eth4/0
  peer_type: server
  description: UNIX_R5C7U1-2_CAMSYSPIVOT1_Eth4/0
  shutdown: false
  type: switched
  mode: access
  vlans: '592'
  spanning_tree_portfast: edge
- name: Ethernet4
  peer: UNIX_R5C7U1-2_CAMSYSPIVOT1
  peer_interface: Eth0/4
  peer_type: server
  description: UNIX_R5C7U1-2_CAMSYSPIVOT1_Eth0/4
  shutdown: false
  type: switched
  mode: access
  vlans: '922'
  spanning_tree_portfast: edge
- name: Ethernet5
  peer: UNIX_R5C7U1-2_CAMSYSPIVOT2
  peer_interface: Eth0/3
  peer_type: server
  description: UNIX_R5C7U1-2_CAMSYSPIVOT2_Eth0/3
  shutdown: false
  type: switched
  mode: access
  vlans: '553'
  spanning_tree_portfast: edge
- name: Ethernet6
  peer: UNIX_R5C7U1-2_CAMSYSPIVOT2
  peer_interface: Eth0/1
  peer_type: server
  description: UNIX_R5C7U1-2_CAMSYSPIVOT2_Eth0/1
  shutdown: false
  type: switched
  mode: access
  vlans: '1001'
  spanning_tree_portfast: edge
- name: Ethernet7
  peer: UNIX_R5C7U1-2_CAMSYSPIVOT2
  peer_interface: Eth4/0
  peer_type: server
  description: UNIX_R5C7U1-2_CAMSYSPIVOT2_Eth4/0
  shutdown: false
  type: switched
  mode: access
  vlans: '592'
  spanning_tree_portfast: edge
- name: Ethernet8
  peer: UNIX_R5C7U1-2_CAMSYSPIVOT2
  peer_interface: Eth0/4
  peer_type: server
  description: UNIX_R5C7U1-2_CAMSYSPIVOT2_Eth0/4
  shutdown: false
  type: switched
  mode: access
  vlans: '922'
  spanning_tree_portfast: edge
mlag_configuration:
  domain_id: MLAG
  local_interface: Vlan4094
  peer_address: 192.168.0.58
  peer_link: Port-Channel47
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
ip_igmp_snooping:
  globally_enabled: true
