---
- name: Configlet upload 
  hosts: cvaas
  connection: local
  gather_facts: no
  tasks:

  - name: "Deploying configurations to CVaaS"
    import_role:
      name: arista.avd.eos_config_deploy_cvp
    vars:
      container_root: 'FABRIC'
      configlets_prefix: 'test'
      device_filter:
        - 'leaf1a-dc1'
      state: present
      execute_tasks: false
      is_deployed: false